apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
#namePrefix: prod-
resources:
- ../../base
#  - pvc.yaml
patches:
- path: edu-user-config.yaml
- path: edu-user-deploy.yaml
- path: edu-user-ingress.yaml
- path: edu-user-svc.yaml
images:
- name: adelacho/k8s-edu-user
  newTag: "202501221604"
